## NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one opf their main building blocks. 

In [1]:
import numpy as np

In [3]:
mylist = [i for i in range(10)]
type(mylist)

list

In [4]:
mylist*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [6]:
myarray**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
mymatrix = np.array([[0,1,5],[-2,1,4],[7,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [8]:
mymatrix[:,0:1]

array([[ 0],
       [-2],
       [ 7]])

In [11]:
mymatrix[:,1:2] 

array([[1],
       [1],
       [8]])

In [12]:
mymatrix[0:2:,2:3] 

array([[5],
       [4]])

In [16]:
mymatrix[:,:]

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

^ all columns 

## Built in Methods
there are lots of built-in ways to generate Arrays

## arrange
return evenly spaced values within a given interval

In [18]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

## zeros and ones
Generate arrays of zeros or ones

In [25]:
Z = np.zeros(4)
Z

array([0., 0., 0., 0.])

In [26]:
Z3 = np.zeros((3,3))
Z3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [28]:
O6 = np.ones((6,6))
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## linspace 
return evenly spaced numbers over a specified interval.

In [29]:
L = np.linspace(0,25,10)
L

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [30]:
L = np.linspace(0,25,25)
L

array([ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667,
        5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ,
       10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333,
       15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667,
       20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ])

In [31]:
L = np.linspace(1,25,25)
L

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [34]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [35]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

## eye 
creates an identity matrix

In [38]:
I2 =np.eye(2) 
I2

array([[1., 0.],
       [0., 1.]])

In [39]:
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
I43 = np.eye(4,3)
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [41]:
I43[0:2,0:2] 

array([[1., 0.],
       [0., 1.]])

## Random 
numpy also has lots of ways to create random number arrays:

## rand 

create an array of the given shape and populate it with randrom samples from a uniform distribution over [0,1)

In [42]:
import random

In [43]:
arr = np.random.rand(3,4)
arr 

array([[0.14832471, 0.74380254, 0.05410669, 0.43448624],
       [0.40478451, 0.04936158, 0.68042229, 0.46536741],
       [0.36666433, 0.91962622, 0.16146395, 0.3855368 ]])

In [44]:
from numpy.random import rand 

In [45]:
arr_simple = rand(3,4)
arr_simple 

array([[0.49529923, 0.60290216, 0.73583156, 0.59316527],
       [0.32779741, 0.34879348, 0.07837915, 0.42035668],
       [0.35852711, 0.1660998 , 0.90529773, 0.65261517]])

## randn 
return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [46]:
from numpy.random import randn 

In [47]:
mat = randn(3,2)
mat

array([[ 1.10310402,  0.65044531],
       [ 0.15943321,  0.91218031],
       [ 0.4086291 , -2.35842877]])